/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWaitlistRouteImport } from './routes/_app.waitlist'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSpacesRouteImport } from './routes/_app.spaces'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'
import { Route as AppMetricsTechnicalRouteImport } from './routes/_app.metrics.technical'
import { Route as AppMetricsAppRouteImport } from './routes/_app.metrics.app'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWaitlistRoute = AppWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppMetricsTechnicalRoute = AppMetricsTechnicalRouteImport.update({
  id: '/metrics/technical',
  path: '/metrics/technical',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsAppRoute = AppMetricsAppRouteImport.update({
  id: '/metrics/app',
  path: '/metrics/app',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/users': typeof AppUsersRouteWithChildren
  '/waitlist': typeof AppWaitlistRoute
  '/': typeof AppIndexRoute
  '/metrics/app': typeof AppMetricsAppRoute
  '/metrics/technical': typeof AppMetricsTechnicalRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings': typeof AppSettingsRoute
  '/spaces': typeof AppSpacesRoute
  '/waitlist': typeof AppWaitlistRoute
  '/': typeof AppIndexRoute
  '/metrics/app': typeof AppMetricsAppRoute
  '/metrics/technical': typeof AppMetricsTechnicalRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spaces': typeof AppSpacesRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/waitlist': typeof AppWaitlistRoute
  '/_app/': typeof AppIndexRoute
  '/_app/metrics/app': typeof AppMetricsAppRoute
  '/_app/metrics/technical': typeof AppMetricsTechnicalRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/setup'
    | '/settings'
    | '/spaces'
    | '/users'
    | '/waitlist'
    | '/'
    | '/metrics/app'
    | '/metrics/technical'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/settings'
    | '/spaces'
    | '/waitlist'
    | '/'
    | '/metrics/app'
    | '/metrics/technical'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/settings'
    | '/_app/spaces'
    | '/_app/users'
    | '/_app/waitlist'
    | '/_app/'
    | '/_app/metrics/app'
    | '/_app/metrics/technical'
    | '/_app/users/$userId'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waitlist': {
      id: '/_app/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AppWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spaces': {
      id: '/_app/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/metrics/technical': {
      id: '/_app/metrics/technical'
      path: '/metrics/technical'
      fullPath: '/metrics/technical'
      preLoaderRoute: typeof AppMetricsTechnicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics/app': {
      id: '/_app/metrics/app'
      path: '/metrics/app'
      fullPath: '/metrics/app'
      preLoaderRoute: typeof AppMetricsAppRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpacesRoute: typeof AppSpacesRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppWaitlistRoute: typeof AppWaitlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMetricsAppRoute: typeof AppMetricsAppRoute
  AppMetricsTechnicalRoute: typeof AppMetricsTechnicalRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppSpacesRoute: AppSpacesRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppWaitlistRoute: AppWaitlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppMetricsAppRoute: AppMetricsAppRoute,
  AppMetricsTechnicalRoute: AppMetricsTechnicalRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
