// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: client.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct Client_MessageContentPayload: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var voice: Client_MessageVoiceContent {
    get {_storage._voice ?? Client_MessageVoiceContent()}
    set {_uniqueStorage()._voice = newValue}
  }
  /// Returns true if `voice` has been explicitly set.
  public var hasVoice: Bool {_storage._voice != nil}
  /// Clears the value of `voice`. Subsequent reads from it will return its default value.
  public mutating func clearVoice() {_uniqueStorage()._voice = nil}

  public var actions: MessageActions {
    get {_storage._actions ?? MessageActions()}
    set {_uniqueStorage()._actions = newValue}
  }
  /// Returns true if `actions` has been explicitly set.
  public var hasActions: Bool {_storage._actions != nil}
  /// Clears the value of `actions`. Subsequent reads from it will return its default value.
  public mutating func clearActions() {_uniqueStorage()._actions = nil}

  public var replies: MessageReplies {
    get {_storage._replies ?? MessageReplies()}
    set {_uniqueStorage()._replies = newValue}
  }
  /// Returns true if `replies` has been explicitly set.
  public var hasReplies: Bool {_storage._replies != nil}
  /// Clears the value of `replies`. Subsequent reads from it will return its default value.
  public mutating func clearReplies() {_uniqueStorage()._replies = nil}

  public var serviceMessage: MessageService {
    get {_storage._serviceMessage ?? MessageService()}
    set {_uniqueStorage()._serviceMessage = newValue}
  }
  /// Returns true if `serviceMessage` has been explicitly set.
  public var hasServiceMessage: Bool {_storage._serviceMessage != nil}
  /// Clears the value of `serviceMessage`. Subsequent reads from it will return its default value.
  public mutating func clearServiceMessage() {_uniqueStorage()._serviceMessage = nil}

  public var subthread: MessageSubthread {
    get {_storage._subthread ?? MessageSubthread()}
    set {_uniqueStorage()._subthread = newValue}
  }
  /// Returns true if `subthread` has been explicitly set.
  public var hasSubthread: Bool {_storage._subthread != nil}
  /// Clears the value of `subthread`. Subsequent reads from it will return its default value.
  public mutating func clearSubthread() {_uniqueStorage()._subthread = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public nonisolated struct Client_MessageVoiceContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var voiceID: Int64 = 0

  public var duration: Int32 = 0

  public var waveform: Data = Data()

  public var mimeType: String = String()

  public var cdnURL: String = String()

  public var localRelativePath: String = String()

  public var size: Int64 = 0

  public var transcription: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Client_Transaction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var date: Int64 = 0

  public var call: RpcCall {
    get {_call ?? RpcCall()}
    set {_call = newValue}
  }
  /// Returns true if `call` has been explicitly set.
  public var hasCall: Bool {self._call != nil}
  /// Clears the value of `call`. Subsequent reads from it will return its default value.
  public mutating func clearCall() {self._call = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _call: RpcCall? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "client"

nonisolated extension Client_MessageContentPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessageContentPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}voice\0\u{1}actions\0\u{1}replies\0\u{3}service_message\0\u{1}subthread\0")

  fileprivate class _StorageClass {
    var _voice: Client_MessageVoiceContent? = nil
    var _actions: MessageActions? = nil
    var _replies: MessageReplies? = nil
    var _serviceMessage: MessageService? = nil
    var _subthread: MessageSubthread? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _voice = source._voice
      _actions = source._actions
      _replies = source._replies
      _serviceMessage = source._serviceMessage
      _subthread = source._subthread
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._voice) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._actions) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._replies) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._serviceMessage) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._subthread) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._voice {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._actions {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._replies {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._serviceMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._subthread {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Client_MessageContentPayload, rhs: Client_MessageContentPayload) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._voice != rhs_storage._voice {return false}
        if _storage._actions != rhs_storage._actions {return false}
        if _storage._replies != rhs_storage._replies {return false}
        if _storage._serviceMessage != rhs_storage._serviceMessage {return false}
        if _storage._subthread != rhs_storage._subthread {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Client_MessageVoiceContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessageVoiceContent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}voice_id\0\u{1}duration\0\u{1}waveform\0\u{3}mime_type\0\u{3}cdn_url\0\u{3}local_relative_path\0\u{1}size\0\u{1}transcription\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.voiceID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.duration) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.waveform) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.cdnURL) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.localRelativePath) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.size) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.transcription) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.voiceID != 0 {
      try visitor.visitSingularInt64Field(value: self.voiceID, fieldNumber: 1)
    }
    if self.duration != 0 {
      try visitor.visitSingularInt32Field(value: self.duration, fieldNumber: 2)
    }
    if !self.waveform.isEmpty {
      try visitor.visitSingularBytesField(value: self.waveform, fieldNumber: 3)
    }
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 4)
    }
    if !self.cdnURL.isEmpty {
      try visitor.visitSingularStringField(value: self.cdnURL, fieldNumber: 5)
    }
    if !self.localRelativePath.isEmpty {
      try visitor.visitSingularStringField(value: self.localRelativePath, fieldNumber: 6)
    }
    if self.size != 0 {
      try visitor.visitSingularInt64Field(value: self.size, fieldNumber: 7)
    }
    if !self.transcription.isEmpty {
      try visitor.visitSingularStringField(value: self.transcription, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Client_MessageVoiceContent, rhs: Client_MessageVoiceContent) -> Bool {
    if lhs.voiceID != rhs.voiceID {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.waveform != rhs.waveform {return false}
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.cdnURL != rhs.cdnURL {return false}
    if lhs.localRelativePath != rhs.localRelativePath {return false}
    if lhs.size != rhs.size {return false}
    if lhs.transcription != rhs.transcription {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Client_Transaction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Transaction"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}date\0\u{1}call\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.date) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._call) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.date != 0 {
      try visitor.visitSingularInt64Field(value: self.date, fieldNumber: 2)
    }
    try { if let v = self._call {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Client_Transaction, rhs: Client_Transaction) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.date != rhs.date {return false}
    if lhs._call != rhs._call {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
