import { normalizeUsername } from "@in/server/utils/normalize"

export const RESERVED_USERNAMES = [
  "about",
  "admin",
  "adminbot",
  "administrator",
  "all",
  "api",
  "app",
  "auth",
  "bot",
  "bots",
  "channel",
  "channels",
  "chat",
  "chats",
  "contact",
  "dev",
  "developer",
  "developers",
  "docs",
  "download",
  "email",
  "feedback",
  "founder",
  "group",
  "groups",
  "help",
  "helpbot",
  "hello",
  "hey",
  "hi",
  "home",
  "info",
  "inline",
  "inline_bot",
  "inline_chat",
  "inline_support",
  "inlineadmin",
  "inlineapp",
  "inlinebot",
  "inlinechat",
  "inlinechatbot",
  "inlinehq",
  "inlinesupport",
  "invite",
  "legal",
  "login",
  "logout",
  "me",
  "message",
  "messages",
  "morajabi",
  "new",
  "news",
  "notifications",
  "null",
  "official",
  "officialbot",
  "privacy",
  "profile",
  "root",
  "search",
  "security",
  "settings",
  "signup",
  "space",
  "spaces",
  "staff",
  "status",
  "statusbot",
  "support",
  "support_bot",
  "supportbot",
  "system",
  "systembot",
  "team",
  "terms",
  "thread",
  "threads",
  "undefined",
  "updates",
  "updatesbot",
  "user",
  "username",
  "users",
  "welcome",
] as const

const reserved = new Set<string>(RESERVED_USERNAMES)

export const isReservedUsername = (username: string): boolean => {
  return reserved.has(normalizeUsername(username).toLowerCase())
}
