export const markdownFixture = [
  "# Heading",
  "",
  "**bold** _italic_ <u>underline</u> ~~strike~~ ==highlight== `code`",
  "",
  "[Person](inline://user?id=42) [[Thread]](inline://chat?id=123) [link](https://example.com)",
  "",
  "- [x] checked",
  "- [ ] todo",
  "  - nested",
  "",
  "> quote",
  "",
  "---",
  "",
  "| Task | State |",
  "| --- | --- |",
  "| Build | Done |",
  "",
  "![image](https://example.com/image.png)",
  "",
  "$x^2$",
  "",
  "$$",
  "E=mc^2",
  "$$",
  "",
  "<details open>",
  '<summary kind="progress">Working</summary>',
  "",
  "```ts",
  "  const x = 1",
  "```",
  "",
  "</details>",
  "",
  "<footer>Attribution</footer>",
  "",
].join("\n")
