CREATE TABLE "chat_id_reservation" (
	"chat_id" integer PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"claimed_at" timestamp (3),
	"expires_at" timestamp (3) NOT NULL,
	"created_at" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chats" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "chat_id_reservation" ADD CONSTRAINT "chat_id_reservation_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;