// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "server.proto" (package "server", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message server.ServerUpdate
 */
export interface ServerUpdate {
    /**
     * @generated from protobuf field: int64 date = 1;
     */
    date: bigint;
    /**
     * @generated from protobuf field: int32 seq = 2;
     */
    seq: number;
    /**
     * @generated from protobuf oneof: update
     */
    update: {
        oneofKind: "newMessage";
        /**
         * @generated from protobuf field: server.ServerChatUpdateNewMessage new_message = 4;
         */
        newMessage: ServerChatUpdateNewMessage;
    } | {
        oneofKind: "editMessage";
        /**
         * @generated from protobuf field: server.ServerChatUpdateEditMessage edit_message = 5;
         */
        editMessage: ServerChatUpdateEditMessage;
    } | {
        oneofKind: "deleteMessages";
        /**
         * @generated from protobuf field: server.ServerChatUpdateDeleteMessages delete_messages = 6;
         */
        deleteMessages: ServerChatUpdateDeleteMessages;
    } | {
        oneofKind: "deleteChat";
        /**
         * @generated from protobuf field: server.ServerChatUpdateDeleteChat delete_chat = 7;
         */
        deleteChat: ServerChatUpdateDeleteChat;
    } | {
        oneofKind: "spaceRemoveMember";
        /**
         * Space updates
         *
         * @generated from protobuf field: server.ServerSpaceUpdateRemoveMember space_remove_member = 8;
         */
        spaceRemoveMember: ServerSpaceUpdateRemoveMember;
    } | {
        oneofKind: undefined;
    };
}
// ------------------------------------------------------------
// Chat updates
// ------------------------------------------------------------

/**
 * Update for a chat when a message is created
 *
 * @generated from protobuf message server.ServerChatUpdateNewMessage
 */
export interface ServerChatUpdateNewMessage {
    /**
     * @generated from protobuf field: int64 chat_id = 1;
     */
    chatId: bigint;
    /**
     * @generated from protobuf field: int64 msg_id = 2;
     */
    msgId: bigint;
}
/**
 * Update for a chat when a message is edited
 *
 * @generated from protobuf message server.ServerChatUpdateEditMessage
 */
export interface ServerChatUpdateEditMessage {
    /**
     * @generated from protobuf field: int64 chat_id = 1;
     */
    chatId: bigint;
    /**
     * @generated from protobuf field: int64 msg_id = 2;
     */
    msgId: bigint;
}
/**
 * Update for a chat when messages are deleted
 *
 * @generated from protobuf message server.ServerChatUpdateDeleteMessages
 */
export interface ServerChatUpdateDeleteMessages {
    /**
     * @generated from protobuf field: int64 chat_id = 1;
     */
    chatId: bigint;
    /**
     * @generated from protobuf field: repeated int64 msg_ids = 2;
     */
    msgIds: bigint[];
}
/**
 * Update for a chat when it is deleted
 *
 * @generated from protobuf message server.ServerChatUpdateDeleteChat
 */
export interface ServerChatUpdateDeleteChat {
    /**
     * @generated from protobuf field: int64 chat_id = 1;
     */
    chatId: bigint;
}
// ------------------------------------------------------------
// Space updates
// ------------------------------------------------------------

/**
 * Update for a space when a member is removed
 *
 * @generated from protobuf message server.ServerSpaceUpdateRemoveMember
 */
export interface ServerSpaceUpdateRemoveMember {
    /**
     * @generated from protobuf field: int64 space_id = 1;
     */
    spaceId: bigint;
    /**
     * @generated from protobuf field: int64 user_id = 2;
     */
    userId: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class ServerUpdate$Type extends MessageType<ServerUpdate> {
    constructor() {
        super("server.ServerUpdate", [
            { no: 1, name: "date", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "seq", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "new_message", kind: "message", oneof: "update", T: () => ServerChatUpdateNewMessage },
            { no: 5, name: "edit_message", kind: "message", oneof: "update", T: () => ServerChatUpdateEditMessage },
            { no: 6, name: "delete_messages", kind: "message", oneof: "update", T: () => ServerChatUpdateDeleteMessages },
            { no: 7, name: "delete_chat", kind: "message", oneof: "update", T: () => ServerChatUpdateDeleteChat },
            { no: 8, name: "space_remove_member", kind: "message", oneof: "update", T: () => ServerSpaceUpdateRemoveMember }
        ]);
    }
    create(value?: PartialMessage<ServerUpdate>): ServerUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.date = 0n;
        message.seq = 0;
        message.update = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ServerUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerUpdate): ServerUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 date */ 1:
                    message.date = reader.int64().toBigInt();
                    break;
                case /* int32 seq */ 2:
                    message.seq = reader.int32();
                    break;
                case /* server.ServerChatUpdateNewMessage new_message */ 4:
                    message.update = {
                        oneofKind: "newMessage",
                        newMessage: ServerChatUpdateNewMessage.internalBinaryRead(reader, reader.uint32(), options, (message.update as any).newMessage)
                    };
                    break;
                case /* server.ServerChatUpdateEditMessage edit_message */ 5:
                    message.update = {
                        oneofKind: "editMessage",
                        editMessage: ServerChatUpdateEditMessage.internalBinaryRead(reader, reader.uint32(), options, (message.update as any).editMessage)
                    };
                    break;
                case /* server.ServerChatUpdateDeleteMessages delete_messages */ 6:
                    message.update = {
                        oneofKind: "deleteMessages",
                        deleteMessages: ServerChatUpdateDeleteMessages.internalBinaryRead(reader, reader.uint32(), options, (message.update as any).deleteMessages)
                    };
                    break;
                case /* server.ServerChatUpdateDeleteChat delete_chat */ 7:
                    message.update = {
                        oneofKind: "deleteChat",
                        deleteChat: ServerChatUpdateDeleteChat.internalBinaryRead(reader, reader.uint32(), options, (message.update as any).deleteChat)
                    };
                    break;
                case /* server.ServerSpaceUpdateRemoveMember space_remove_member */ 8:
                    message.update = {
                        oneofKind: "spaceRemoveMember",
                        spaceRemoveMember: ServerSpaceUpdateRemoveMember.internalBinaryRead(reader, reader.uint32(), options, (message.update as any).spaceRemoveMember)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 date = 1; */
        if (message.date !== 0n)
            writer.tag(1, WireType.Varint).int64(message.date);
        /* int32 seq = 2; */
        if (message.seq !== 0)
            writer.tag(2, WireType.Varint).int32(message.seq);
        /* server.ServerChatUpdateNewMessage new_message = 4; */
        if (message.update.oneofKind === "newMessage")
            ServerChatUpdateNewMessage.internalBinaryWrite(message.update.newMessage, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* server.ServerChatUpdateEditMessage edit_message = 5; */
        if (message.update.oneofKind === "editMessage")
            ServerChatUpdateEditMessage.internalBinaryWrite(message.update.editMessage, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* server.ServerChatUpdateDeleteMessages delete_messages = 6; */
        if (message.update.oneofKind === "deleteMessages")
            ServerChatUpdateDeleteMessages.internalBinaryWrite(message.update.deleteMessages, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* server.ServerChatUpdateDeleteChat delete_chat = 7; */
        if (message.update.oneofKind === "deleteChat")
            ServerChatUpdateDeleteChat.internalBinaryWrite(message.update.deleteChat, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* server.ServerSpaceUpdateRemoveMember space_remove_member = 8; */
        if (message.update.oneofKind === "spaceRemoveMember")
            ServerSpaceUpdateRemoveMember.internalBinaryWrite(message.update.spaceRemoveMember, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerUpdate
 */
export const ServerUpdate = new ServerUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerChatUpdateNewMessage$Type extends MessageType<ServerChatUpdateNewMessage> {
    constructor() {
        super("server.ServerChatUpdateNewMessage", [
            { no: 1, name: "chat_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ServerChatUpdateNewMessage>): ServerChatUpdateNewMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chatId = 0n;
        message.msgId = 0n;
        if (value !== undefined)
            reflectionMergePartial<ServerChatUpdateNewMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerChatUpdateNewMessage): ServerChatUpdateNewMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 chat_id */ 1:
                    message.chatId = reader.int64().toBigInt();
                    break;
                case /* int64 msg_id */ 2:
                    message.msgId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerChatUpdateNewMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 chat_id = 1; */
        if (message.chatId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.chatId);
        /* int64 msg_id = 2; */
        if (message.msgId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.msgId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerChatUpdateNewMessage
 */
export const ServerChatUpdateNewMessage = new ServerChatUpdateNewMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerChatUpdateEditMessage$Type extends MessageType<ServerChatUpdateEditMessage> {
    constructor() {
        super("server.ServerChatUpdateEditMessage", [
            { no: 1, name: "chat_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "msg_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ServerChatUpdateEditMessage>): ServerChatUpdateEditMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chatId = 0n;
        message.msgId = 0n;
        if (value !== undefined)
            reflectionMergePartial<ServerChatUpdateEditMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerChatUpdateEditMessage): ServerChatUpdateEditMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 chat_id */ 1:
                    message.chatId = reader.int64().toBigInt();
                    break;
                case /* int64 msg_id */ 2:
                    message.msgId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerChatUpdateEditMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 chat_id = 1; */
        if (message.chatId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.chatId);
        /* int64 msg_id = 2; */
        if (message.msgId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.msgId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerChatUpdateEditMessage
 */
export const ServerChatUpdateEditMessage = new ServerChatUpdateEditMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerChatUpdateDeleteMessages$Type extends MessageType<ServerChatUpdateDeleteMessages> {
    constructor() {
        super("server.ServerChatUpdateDeleteMessages", [
            { no: 1, name: "chat_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "msg_ids", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ServerChatUpdateDeleteMessages>): ServerChatUpdateDeleteMessages {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chatId = 0n;
        message.msgIds = [];
        if (value !== undefined)
            reflectionMergePartial<ServerChatUpdateDeleteMessages>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerChatUpdateDeleteMessages): ServerChatUpdateDeleteMessages {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 chat_id */ 1:
                    message.chatId = reader.int64().toBigInt();
                    break;
                case /* repeated int64 msg_ids */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.msgIds.push(reader.int64().toBigInt());
                    else
                        message.msgIds.push(reader.int64().toBigInt());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerChatUpdateDeleteMessages, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 chat_id = 1; */
        if (message.chatId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.chatId);
        /* repeated int64 msg_ids = 2; */
        if (message.msgIds.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.msgIds.length; i++)
                writer.int64(message.msgIds[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerChatUpdateDeleteMessages
 */
export const ServerChatUpdateDeleteMessages = new ServerChatUpdateDeleteMessages$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerChatUpdateDeleteChat$Type extends MessageType<ServerChatUpdateDeleteChat> {
    constructor() {
        super("server.ServerChatUpdateDeleteChat", [
            { no: 1, name: "chat_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ServerChatUpdateDeleteChat>): ServerChatUpdateDeleteChat {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chatId = 0n;
        if (value !== undefined)
            reflectionMergePartial<ServerChatUpdateDeleteChat>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerChatUpdateDeleteChat): ServerChatUpdateDeleteChat {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 chat_id */ 1:
                    message.chatId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerChatUpdateDeleteChat, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 chat_id = 1; */
        if (message.chatId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.chatId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerChatUpdateDeleteChat
 */
export const ServerChatUpdateDeleteChat = new ServerChatUpdateDeleteChat$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServerSpaceUpdateRemoveMember$Type extends MessageType<ServerSpaceUpdateRemoveMember> {
    constructor() {
        super("server.ServerSpaceUpdateRemoveMember", [
            { no: 1, name: "space_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ServerSpaceUpdateRemoveMember>): ServerSpaceUpdateRemoveMember {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.spaceId = 0n;
        message.userId = 0n;
        if (value !== undefined)
            reflectionMergePartial<ServerSpaceUpdateRemoveMember>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ServerSpaceUpdateRemoveMember): ServerSpaceUpdateRemoveMember {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 space_id */ 1:
                    message.spaceId = reader.int64().toBigInt();
                    break;
                case /* int64 user_id */ 2:
                    message.userId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ServerSpaceUpdateRemoveMember, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 space_id = 1; */
        if (message.spaceId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.spaceId);
        /* int64 user_id = 2; */
        if (message.userId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message server.ServerSpaceUpdateRemoveMember
 */
export const ServerSpaceUpdateRemoveMember = new ServerSpaceUpdateRemoveMember$Type();
