export const REQUIRED_PRODUCTION_VARIABLES = [
  "DATABASE_URL",
  "ENCRYPTION_KEY",
  "AMAZON_ACCESS_KEY",
  "AMAZON_SECRET_ACCESS_KEY",
  "SES_ACCESS_KEY_ID",
  "SES_SECRET_ACCESS_KEY",
  "TWILIO_SID",
  "TWILIO_VERIFY_SERVICE_SID",
  "SENTRY_DSN",
  "RESEND_API_KEY",
  "APN_KEY",
  "APN_KEY_ID",
  "APN_TEAM_ID",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "R2_BUCKET",
  "R2_ENDPOINT",
  "PRELUDE_API_TOKEN",
] as const

export type RequiredProductionVariable =
  (typeof REQUIRED_PRODUCTION_VARIABLES)[number]
