/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppChatPeerKindPeerIdRouteImport } from './routes/_app.chat.$peerKind.$peerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppChatPeerKindPeerIdRoute = AppChatPeerKindPeerIdRouteImport.update({
  id: '/chat/$peerKind/$peerId',
  path: '/chat/$peerKind/$peerId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chats': typeof AppChatsRoute
  '/settings': typeof AppSettingsRoute
  '/chat/$peerKind/$peerId': typeof AppChatPeerKindPeerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chats': typeof AppChatsRoute
  '/settings': typeof AppSettingsRoute
  '/chat/$peerKind/$peerId': typeof AppChatPeerKindPeerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chats': typeof AppChatsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/chat/$peerKind/$peerId': typeof AppChatPeerKindPeerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/chats' | '/settings' | '/chat/$peerKind/$peerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/chats' | '/settings' | '/chat/$peerKind/$peerId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chats'
    | '/_app/settings'
    | '/_app/chat/$peerKind/$peerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$peerKind/$peerId': {
      id: '/_app/chat/$peerKind/$peerId'
      path: '/chat/$peerKind/$peerId'
      fullPath: '/chat/$peerKind/$peerId'
      preLoaderRoute: typeof AppChatPeerKindPeerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppChatPeerKindPeerIdRoute: typeof AppChatPeerKindPeerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppChatPeerKindPeerIdRoute: AppChatPeerKindPeerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
